name: Build and Release OGDP

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CI: true
  NODE_OPTIONS: --max_old_space_size=4096
  GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Add this line to make token available

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            icon-cmd: sudo apt-get install -y imagemagick
          - os: windows-latest
            icon-cmd: choco install imagemagick -y
          - os: macos-latest
            icon-cmd: brew install imagemagick
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install System Dependencies
        run: ${{ matrix.icon-cmd }}

      - name: Install Project Dependencies
        run: |
          npm ci
          npm run postinstall

      - name: Build Electron App
        run: npm run build
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
          # Additional env vars for macOS code signing (optional)
          CSC_IDENTITY_AUTO_DISCOVERY: false  # Disable if you're not code signing

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OGDP-${{ runner.os }}-v${{ github.run_number }}
          path: |
            dist/*
            !dist/**/*.blockmap
          retention-days: 7
          compression-level: 9

      - name: Upload Build Metadata
        uses: actions/upload-artifact@v4
        with:
          name: build-meta-${{ runner.os }}
          path: |
            build/logs/
            dist/*.yml
            dist/*.json
          retention-days: 30
