name: Build Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          npm run postinstall

      - name: Build with Electron Builder
        run: npm run dist
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ runner.os }}
          path: dist/
          retention-days: 5
